const { test, expect } = require("@playwright/test");
const path = require("node:path");

test("adversarial ZIP: valid capture and duplicate index refusal", async ({
  browser,
}) => {
  const directory = process.env.CHITAOZINHO_ADVERSARIAL_FIXTURE_DIR;
  test.skip(
    !directory,
    "Supply local synthetic fixtures generated by the API test",
  );
  for (const viewport of [
    { width: 1440, height: 900 },
    { width: 360, height: 800 },
  ]) {
    // Keep proof requests inside the local mock; the offline worker has separate tests.
    const context = await browser.newContext({
      viewport,
      serviceWorkers: "block",
    });
    const page = await context.newPage();
    const errors = [];
    page.on("pageerror", (error) => errors.push(error.message));
    await page.route("https://api.evidencias.org.br/**", (route) =>
      route.fulfill({
        status: 200,
        contentType: "application/json",
        body: JSON.stringify({ bundle_available: false, attestation_count: 0 }),
      }),
    );
    await page.goto("/validar");
    await page
      .locator("#package")
      .setInputFiles(path.join(directory, "evidence.zip"));
    await page.locator(".verify-button").click();
    await expect(
      page.getByRole("heading", {
        name: "Integridade confirmada",
        exact: true,
      }),
    ).toBeVisible();
    await expect(
      page.getByText("Assinatura consistente com a chave do pacote", {
        exact: true,
      }),
    ).toBeVisible();
    await expect(
      page.getByText(
        "O servidor assinou hashes declarados pelo cliente. Não recebeu, conferiu ou armazenou os arquivos originais.",
        { exact: true },
      ),
    ).toBeVisible();
    await page
      .locator("#package")
      .setInputFiles(path.join(directory, "duplicate-index.zip"));
    await page.locator(".verify-button").click();
    await expect(
      page.getByText(/JSON inválido: package-index.json/),
    ).toBeVisible();
    await expect(
      page.getByRole("heading", {
        name: "Integridade confirmada",
        exact: true,
      }),
    ).toHaveCount(0);
    expect(
      await page.evaluate(
        () =>
          document.documentElement.scrollWidth <=
          document.documentElement.clientWidth,
      ),
    ).toBe(true);
    expect(errors).toEqual([]);
    await context.close();
  }
});
